### ISSUE TITLE
Add missing file - FireGestureRecognizer

### ISSUE THREAD

**Issue by rohanaurora** [nicklockwood/Swiftenstein#1]
Thanks for open sourcing the code. I believe `FireGestureRecognizer` is not added to the repo. Could you please check that.

**Comment by alistairmcmillan** [comment]
`FireGestureRecognizer` is part of another of Nick's repos that you can find here: https://github.com/nicklockwood/FPSControls/blob/master/FPSControls/FireGestureRecognizer.swift

You'll need to update the code though as Swiftenstein seems to be expecting a more recent version of the file. Or you could grab the fork I updated here: https://github.com/alistairmcmillan/FPSControls/blob/master/FPSControls/FireGestureRecognizer.swift

**Comment by nicklockwood** [comment]
Oh, weird. OK, I'll fix that, thanks.

**Comment by nicklockwood** [comment]
Fixed. Thanks for reporting.
